# Generated by Django 4.0.4 on 2022-04-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesh', '0002_uploadmesh'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesh',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mesh',
            name='variant',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='mesh',
            name='color_names',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='uploadmesh',
            name='mesh_file',
            field=models.FileField(upload_to=''),
        ),
    ]
